import type { FanContext, Grounding } from './types';
import type { Snapshot } from './knowledge';
import { normalized } from './safety';
import { guestActions } from './handoffs';

// Reviewed policy answers are independent of an LLM and of prior conversation text.
// A topic matches the fan's wording, then checks its own current source document.
const topics = {
  stroller: { title:'Strollers', match:/\b(strollers?|pushchair|pram|cochecito|carriola|carrito de bebe)\b/, anchor:/permitted.*security/, en:'Strollers are permitted after security screening at entry. You can check a stroller at Guest Services behind section 124.', es:'Se permiten cochecitos después de la revisión de seguridad al entrar. Puedes dejarlos en Guest Services detrás de la sección 124.' },
  elevators: { title:'Elevators', match:/\b(elevators?|lifts?|ascensor(?:es)?|elevador(?:es)?)\b/, anchor:/124.*120.*108/s, en:'Elevators: North Building / Ticket HQ behind 124 serves the 100, Beer Hall 200 and Lofts 300 levels. The Verde Store elevator behind 120 serves its 100 and 200 levels. Three VIP Lobby elevators behind 108 serve the Field Club, main concourse, SHI suites, Austin Telco Terrace and Porch; ticket restrictions apply to club and suite areas.', es:'Ascensores: North Building / Ticket HQ detrás de 124 conecta los niveles 100, Beer Hall 200 y Lofts 300. Verde Store detrás de 120 conecta sus niveles 100 y 200. Los tres ascensores del vestíbulo VIP detrás de 108 conectan Field Club, explanada principal, suites SHI, Austin Telco Terrace y Porch; los clubes y suites requieren el boleto correspondiente.' },
  animals: { title:'Animals', match:/\b(animals?|pets?|dogs?|puppy|esa|emotional support|service animal|perros?|mascota|animal(?:es)?|apoyo emocional)\b/, anchor:/emotional support animals are not permitted/, en:'Pets and emotional support animals (ESAs) are not permitted. Q2 welcomes service animals as defined by the ADA. For service-animal arrangements, contact GuestServices@AustinFC.com before your event.', es:'No se permiten mascotas ni animales de apoyo emocional (ESA). Q2 admite animales de servicio definidos por la ADA. Para adaptaciones, consulta a GuestServices@AustinFC.com antes del evento.' },
  reentry: { title:'Re-Entry Policy', match:/re.?entr(?:y|ar|ada)|\b(?:leave|exit|salir)\b.{0,65}\b(?:come back|return|get back|back in|volver|regresar)\b|\b(?:come back|return|volver|regresar)\b.{0,45}\b(?:halftime|half time|medio tiempo|stadium|estadio)\b/, anchor:/not permitted to exit and re-enter/, en:'Re-entry is not permitted: you cannot leave Q2 Stadium and return using the same ticket, including at halftime.', es:'No se permite volver a entrar: no puedes salir de Q2 Stadium y regresar con el mismo boleto, incluso durante el medio tiempo.' },
  ev: { title:'EV Charging Stations', match:/\b(tesla|electric (?:car|vehicle)|ev charg\w*|ev stations?|cargar.{0,15}(?:auto|coche|tesla)|vehiculo electrico)\b/, anchor:/Eight.*Two.*Six/s, en:'EV charging is available to fans with access to the relevant lot: Ford East has 8 stations via Aguilar Street off Braker Lane; North Lot has 2 and Southwest Lot has 6, both via McKalla Place off Rutland Drive. Your parking access must cover that lot; station availability is not live.', es:'Hay carga para vehículos eléctricos si tienes acceso al lote: Ford East tiene 8 estaciones por Aguilar Street desde Braker Lane; North Lot tiene 2 y Southwest Lot 6, ambos por McKalla Place desde Rutland Drive. Necesitas acceso al lote correspondiente; no hay disponibilidad en vivo.' },
  cashless: { title:'Payment Methods', match:/\b(cashless|cash|payment methods?|pay (?:at|for).{0,25}(?:stands?|concessions?|food)|efectivo|sin efectivo|pagar.{0,30}(?:puesto|comida))\b/, anchor:/cashless.*Apple Pay.*Google Pay/, en:'Q2 Stadium is cashless. Concession purchases accept major credit cards, Apple Pay and Google Pay.', es:'Q2 Stadium no acepta efectivo. Puedes pagar en los puestos con tarjetas de crédito principales, Apple Pay y Google Pay.' },
  cameras: { title:'Cameras', match:/\b(cameras?|dslr|lens|lenses|tripod|monopod|selfie stick|camara|camaras|lente|tripode)\b/, anchor:/removable lenses/, en:'Cameras with professional or removable lenses, camera cases, tripods, monopods and selfie sticks are prohibited. Event photos or videos cannot be used commercially without written approval from Austin FC.', es:'Se prohíben cámaras con lentes profesionales o desmontables, estuches para cámara, trípodes, monopiés y palos para selfies. El uso comercial de fotos o videos requiere aprobación escrita de Austin FC.' },
  drones: { title:'Drones', match:/\b(drones?|uas|uav)\b/, anchor:/prohibited/, en:'Drones and all unmanned aircraft systems are prohibited. A conditional exemption requires Q2 Stadium Security approval in advance.', es:'Se prohíben drones y todos los sistemas de aeronaves no tripuladas. Una excepción condicional requiere aprobación previa de seguridad de Q2 Stadium.' },
  prohibited: { title:'Prohibited Items', match:/\b(guns?|firearms?|weapons?|knives|knife|pepper spray|mace|taser|fireworks|prohibited items?|banned items?|pistola|armas?|cuchillo|articulos prohibidos|umbrella|laptop|tablet|paraguas)\b/, anchor:/Weapons of any kind/, en:'Weapons of any kind are prohibited, including firearms, knives, pepper spray, mace, tasers and replica weapons. Other prohibited items include fireworks, illegal drugs, outside food/drinks (medical accommodations apply), large electronics and umbrellas larger than 48 inches unless purchased at the Verde Store. See the prohibited-items guide for the complete list.', es:'Se prohíben armas de cualquier tipo, incluidas armas de fuego, cuchillos, gas pimienta, mace, tasers y réplicas. También fuegos artificiales, drogas ilegales, comida/bebidas externas (hay adaptaciones médicas), dispositivos electrónicos grandes y paraguas de más de 48 pulgadas salvo los comprados en Verde Store. Consulta la lista completa de artículos prohibidos.' },
  smoking: { title:'Smoking and Tobacco Use Policy', match:/\b(smok(?:e|ing)|vaping|vapes?|weed|cannabis|marijuana|tobacco|fumar|marihuana|tabaco|vapear)\b/, anchor:/smoke-free.*prohibited/s, en:'Q2 is a smoke-free facility: smoking, e-cigarettes and vaporizers are prohibited in all stadium areas. Illegal drugs/substances are also prohibited. This does not confirm permission to smoke cannabis in a parking lot; ask event staff about the lot policy.', es:'Q2 es un recinto libre de humo: se prohíben fumar, cigarrillos electrónicos y vaporizadores en todas las áreas del estadio. También se prohíben drogas y sustancias ilegales. Esto no confirma permiso para fumar cannabis en un estacionamiento; consulta al personal sobre la política del lote.' },
  tailgating: { title:'Tailgating', match:/\b(tailgat\w*|cookout|grill(?:ing)? in.{0,20}(?:lot|parking)|asado.{0,25}estacionamiento)\b/, anchor:/not permitted/, en:'Tailgating is not permitted at Q2 Stadium.', es:'No se permite tailgating (reuniones o asados en el estacionamiento) en Q2 Stadium.' },
  sunscreen: { title:'Sunscreen', match:/\b(sunscreen|sunblock|protector solar|bloqueador)\b/, anchor:/aerosol sunscreen is prohibited/, en:'Sunscreen is permitted, but aerosol sunscreen is prohibited. Bring a non-aerosol product.', es:'Se permite protector solar, pero no en aerosol. Lleva un producto que no sea aerosol.' },
  children: { title:'Children/Infants', match:/\b(children|infants?|kids? (?:policy|ticket)|child.{0,25}ticket|ticket.{0,25}(?:child|kid|toddler|baby|year.old)|(?:[0-9]+|two|three|dos|tres)[ -](?:year[ -]old|anos)|ninos?.{0,25}(?:boleto|entrada)|(?:boleto|entrada).{0,25}(?:hijo|hija|nino|bebe)|minor|under 14)\b/, anchor:/ages 2 and under.*lap/s, en:'Children age 2 and under do not need a ticket if they sit on a parent or legal guardian’s lap. A 3-year-old needs a ticket. The published general guidance is that children under 14 should be accompanied by an adult; a parent or guardian makes that decision. Contact-information wristbands are available at Guest Services behind 124.', es:'Los niños de 2 años o menos no necesitan boleto si se sientan en el regazo de su padre, madre o tutor legal. Un niño de 3 años necesita boleto. La guía recomienda que los menores de 14 estén acompañados por un adulto; la decisión corresponde a su padre o tutor. Hay pulseras con datos de contacto en Guest Services detrás de 124.' },
  restrooms: { title:'Restrooms', match:/\b(restrooms?|bathrooms?|toilets?|banos?|sanitarios?|aseos?)\b/, anchor:/103 and 128/, en:'Accessible restrooms are throughout the stadium. All-gender restrooms are behind sections 103 and 128. A family restroom is confirmed behind 121. Ask nearby staff for the closest restroom from your section; the guide does not support a precise walking route.', es:'Hay baños accesibles en todo el estadio. Los baños de todos los géneros están detrás de las secciones 103 y 128. Hay un baño familiar confirmado detrás de 121. Pide al personal cercano indicaciones al baño más próximo desde tu sección; la guía no permite dar una ruta exacta a pie.' },
  phonecharge: { title:'Phone Charging Stations', match:/\b(?:charge|charging|charger|cargar|cargador)\b.{0,30}\b(?:phone|iphone|android|telefono|celular)\b|\b(?:phone|iphone|android|telefono|celular)\b.{0,30}\b(?:charge|charging|charger|cargar|cargador)\b/, anchor:/121.*Lexus/s, en:'Inside the stadium, phone charging stations are behind section 121 on the main concourse and inside Lexus Club (club access required). They support Apple and Android devices.', es:'Dentro del estadio hay estaciones de carga para Apple y Android detrás de la sección 121 en la explanada principal y dentro de Lexus Club (requiere acceso al club).' },
  weatherpolicy: { title:'Weather', match:/\b(weather policy|rain policy|rain or shine|politica (?:de|del) clima|politica de lluvia)\b|(?:play|played|cancel|postpon|juega|juegan|cancela).{0,35}(?:rain|lluvia)|(?:rain|lluvia).{0,35}(?:cancel|postpon|policy)/, anchor:/rain or shine/, en:'Q2 soccer matches and other events are rain or shine. For inclement-weather changes, check official Q2 Stadium announcements and follow event staff. The published policy does not confirm a cancellation or postponement for your event.', es:'Los partidos y otros eventos en Q2 se realizan con lluvia o sol. Para cambios por mal tiempo, consulta los anuncios oficiales de Q2 Stadium y sigue al personal. La política no confirma una cancelación o aplazamiento de tu evento.' },
  vehicle: { title:'Parking', match:/\b(motorcycles?|motorbike|rv|rvs|recreational vehicle|camper|oversize|motocicleta|casa rodante)\b/, anchor:/./, en:'Use an event-specific parking pass for its assigned lot. The published guide does not confirm motorcycle, RV or oversized-vehicle eligibility; ask Guest Services before buying a pass or arriving with that vehicle.', es:'Usa un pase de estacionamiento para tu evento y el lote asignado. La guía no confirma si admite motocicletas, casas rodantes o vehículos grandes; consulta a Guest Services antes de comprar o llegar con ese vehículo.' },
  entrance: { title:'Gate Opening Times', match:/\b(?:which|nearest|closest|what|que|cual)\b.{0,50}\b(?:gate|entrance|entry|puerta|entrada)\b|\b(?:gate|entrance|puerta)\b.{0,35}\b(?:section|seccion|133|stm|member)\b|\bstm entrance\b/, anchor:/ninety|90/, en:'Use the gate and entry instructions on your ticket and the official stadium map. General gates open 90 minutes before the event, subject to changes. The guide does not confirm a dedicated STM entrance or the nearest gate for that seat.', es:'Usa la puerta e instrucciones de tu boleto y el mapa oficial del estadio. Generalmente las puertas abren 90 minutos antes del evento, sujeto a cambios. La guía no confirma una entrada exclusiva para abonados ni la puerta más cercana a ese asiento.' },
  allergy: { title:'Guest Services – Guest Services Center', match:/\b(peanuts?|nut allergy|allergens?|allerg(?:y|ies)|alergia|alergenos|cacahuate|mani)\b/, anchor:/124/, en:'The published food guide does not provide a verified allergen list. Ask the concession stand directly about ingredients and cross-contact, and ask Guest Services behind 124 for help before ordering. A vegan or gluten-aware label is not an assurance of allergy safety.', es:'La guía de comida no contiene una lista verificada de alérgenos. Pregunta al puesto sobre ingredientes y contacto cruzado y pide ayuda a Guest Services detrás de 124 antes de pedir. Una etiqueta vegana o que evita gluten no garantiza seguridad para alergias.' },
} as const;
export type CatalogTopic = keyof typeof topics;
export function catalogTopics(query:string):CatalogTopic[] {
  const q=normalized(query);
  return (Object.keys(topics) as CatalogTopic[]).filter(t=>topics[t].match.test(q))
    .filter(t=>!(t==='animals' && !topics[t].match.test(q.replace(/\b(?:hot|chili|corn) dogs?\b/g,''))))
    .filter(t=>!(t==='cashless' && /capmetro|umo|fare|train fare|tarifa/.test(q)))
    .filter(t=>!(t==='phonecharge' && /(?:phone|telefono).{0,20}(?:died|dead|sin bateria).{0,35}(?:gate|puerta)/.test(q)))
    .filter(t=>!(t==='restrooms' && /family|familiar|changing|cambiador/.test(q)))
    .filter(t=>!(t==='entrance' && /(?:what time|when|cuando|hora).{0,30}(?:open|abren|abre)/.test(q)));
}
export function catalogGrounding(topic:CatalogTopic,query:string,context:FanContext,k:Snapshot):Grounding {
  const def=topics[topic], es=context.language==='es';
  const doc=k.documents.find(d=>d.title===def.title);
  const verified=!!doc&&def.anchor.test(doc.body);
  const unresolved=['allergy','vehicle','entrance'].includes(topic) || !verified;
  const titles=[def.title,...(topic==='stroller'?['Guest Services – Guest Services Center']:topic==='smoking'?['Prohibited Items']:[])];
  const docs=k.documents.filter(d=>titles.includes(d.title));
  return {route:'stadium',context,answer:verified?def[es?'es':'en']:(es?'Consulta a Guest Services detrás de 124 para confirmar esta política; la versión actual no permite verificarla.':'Ask Guest Services behind 124 to confirm this policy; the current version does not verify it.'),facts:[],cards:[],sources:docs.map(d=>({title:d.title,url:d.url,checkedAt:d.checkedAt})),actions:unresolved?guestActions(es):[]};
}
