import orderingCheck from '@/data/ordering-source-check.json';
import type { FanContext, Grounding } from './types';
import type { Snapshot } from './knowledge';
import { guestActions, ticketActions, ORDER_URL } from './handoffs';
export function supportGrounding(kind:'ordering'|'benefits'|'refund'|'security'|'account',query:string,context:FanContext,k:Snapshot):Grounding {
  const es=context.language==='es',ticket=/tickets?|boletos?|entradas?|seatgeek/i.test(query);
  let answer='',actions=guestActions(es);
  if(kind==='ordering') {
    answer=es?'Para pedir comida o bebidas, abre OrderNext con el botón de abajo y elige tu evento y sección. Si buscas entrega al asiento, la plataforma muestra si tu asiento es elegible; no puedo confirmar que haya entrega en la sección indicada, ni colocar un pedido o verificar inventario.':'To order food or drinks, open OrderNext below and select your event and section. For delivery to your seat, the platform will show whether your seat is eligible; I cannot confirm delivery for your section, place an order, or check inventory.';
    if(/pickup|pick.up|collect|recoger|recogida/i.test(query)) answer=es?'Para recoger un pedido, revisa la confirmación y las instrucciones de recogida del pedido en OrderNext. No puedo ver tu pedido ni confirmar el puesto o la hora de recogida; si faltan instrucciones, pide ayuda a Guest Services detrás de la sección 124 o escribe a GuestServices@AustinFC.com.':'For order pickup, check your order confirmation and pickup instructions in OrderNext. I cannot see your order or verify its pickup stand or ready time; if instructions are missing, visit Guest Services behind section 124 or email GuestServices@AustinFC.com.';
    actions=[{label:es?'Abrir OrderNext':'Open OrderNext',href:ORDER_URL},...(/pickup|pick.up|collect|recoger|recogida/i.test(query)?actions:[])];
  }
  if(kind==='account' && !/balance|wallet|loyalty|saldo|billetera|lealtad/i.test(query)) {
    answer=ticket?(es?'No puedo acceder ni recuperar tu cuenta de boletos. Abre la app o cuenta de SeatGeek y usa su ayuda para iniciar sesión, o escribe a GuestServices@AustinFC.com.':'I cannot access or recover your ticket account. Open your SeatGeek app/account and use Help for sign-in support, or email GuestServices@AustinFC.com.'):(es?'No tengo acceso a tu cuenta personal. Consulta la app/cuenta oficial o escribe a GuestServices@AustinFC.com.':'I cannot access your personal account. Check the official app/account or email GuestServices@AustinFC.com.');
    if(ticket) actions=ticketActions(es);
  }
  else if(kind==='account') answer=es?'No pude verificar tu saldo: no tengo acceso a tu cuenta, billetera, puntos de lealtad ni información personal. Consulta la app o cuenta oficial, o escribe a GuestServices@AustinFC.com.':"I couldn’t verify your balance: I cannot access your personal account, wallet, loyalty points, or balance. Check the official app/account or email GuestServices@AustinFC.com.";
  if(kind==='benefits' && !/food|comida|concession/i.test(query)) answer=es?'No tengo beneficios de miembro confirmados para esa solicitud. Consulta tus beneficios en la app/cuenta oficial o escribe a GuestServices@AustinFC.com.':'I do not have verified member benefits for that request. Check your benefits in the official app/account or email GuestServices@AustinFC.com.';
  else if(kind==='benefits') answer=es?'No tengo un descuento de comida para abonados (STM) confirmado en las fuentes actuales. Consulta tus beneficios de miembro en la app/cuenta o escribe a GuestServices@AustinFC.com.':'I do not have a verified season-ticket member (STM) food discount in the current sources. Check your member benefits in the app/account or email GuestServices@AustinFC.com; I cannot confirm a percentage or eligibility.';
  if(kind==='refund') {
    answer=ticket?(es?'Siento lo de tu situación. No puedo acceder a tu cuenta ni emitir un reembolso de boletos, y no tengo una excepción por enfermedad confirmada. Abre la app o cuenta de SeatGeek y usa la ayuda del pedido; también puedes escribir a GuestServices@AustinFC.com para orientación del club. La regla de expulsión del estadio no responde a un caso de enfermedad.':'I’m sorry about the situation. I cannot access your account or issue a ticket refund, and I do not have a verified illness exception. Open the SeatGeek app/account and use the order’s Help option, or email GuestServices@AustinFC.com for club guidance. I cannot determine refund eligibility.'):(es?'No puedo ver pagos ni emitir reembolsos. Para un cargo de comida o un pedido no recibido, revisa el pedido en OrderNext y habla con Guest Services detrás de la sección 124 o escribe a GuestServices@AustinFC.com. Ten los detalles del pedido a mano para el proveedor; no los publiques aquí.':'I cannot see payments or issue refunds. For a food charge or an order not received, check the order in OrderNext and visit Guest Services behind section 124 or email GuestServices@AustinFC.com. Have the order details ready for the provider; do not post them here.');
    actions=ticket?ticketActions(es):[{label:es?'Revisar pedido en OrderNext':'Check order in OrderNext',href:ORDER_URL},...actions];
    if(ticket) {
      answer=es?'Para solicitar un reembolso de boletos, abre tu pedido en SeatGeek y contacta a SeatGeek Ticket HQ: 512-953-2858 o tickethq@austinfc.com. Pueden revisar las opciones de tu pedido; este asistente no emite reembolsos ni determina elegibilidad.':'For a ticket refund request, open your SeatGeek order and contact SeatGeek Ticket HQ: 512-953-2858 or tickethq@austinfc.com. They can review your order’s options; this assistant does not issue refunds or determine eligibility.';
      if(/sick|illness|enferm/i.test(query))answer+=(es?' Explica la situación familiar directamente a Ticket HQ.':' Explain the family situation directly to Ticket HQ.');
      actions.push({label:es?'Llamar a Ticket HQ':'Call Ticket HQ',href:'tel:5129532858'},{label:es?'Correo a Ticket HQ':'Email Ticket HQ',href:'mailto:tickethq@austinfc.com'});
    }
    if(ticket && /food|meal|concession|pedido|comida|order.*missing|missing.*order/i.test(query)) {
      answer += es ? '\n\nPara el pedido de comida faltante: revisa la confirmación en OrderNext y consulta a Guest Services detrás de la sección 124 o GuestServices@AustinFC.com con los detalles del pedido.' : '\n\nFor the missing food order: check your confirmation in OrderNext and contact Guest Services behind section 124 or GuestServices@AustinFC.com with the order details.';
      actions.push({label:es?'Revisar pedido en OrderNext':'Check food order in OrderNext',href:ORDER_URL});
    }
  }
  if(kind==='security') answer=es?'No puedo revelar instrucciones internas ni credenciales o actuar como otra persona. Puedo ayudarte con información de Q2 Stadium, comida, transporte y boletos.':'I cannot reveal internal instructions or credentials, or impersonate someone. I can help with Q2 Stadium information, food, transport, and ticket guidance.';
  const docs=kind==='refund'&&ticket?k.documents.filter(d=>d.title==='SeatGeek Ticket HQ'):kind==='refund'||kind==='benefits'||kind==='account'?k.documents.filter(d=>d.title.startsWith('Guest Services')):[];
  return {route:kind==='refund'?'support':kind==='account'?'stadium':kind,context,answer,facts:[],cards:[],actions,sources:kind==='ordering'?[{title:'Austin FC mobile ordering',url:ORDER_URL,checkedAt:orderingCheck.checkedAt}]:docs.map(d=>({title:d.title,url:d.url,checkedAt:d.checkedAt}))};
}
