import orderingCheck from '@/data/ordering-source-check.json';
import type { FanContext, Grounding } from './types';
import type { Snapshot } from './knowledge';
import { guestActions, ticketActions, ORDER_URL } from './handoffs';
export function supportGrounding(kind:'ordering'|'benefits'|'refund'|'security'|'account',query:string,context:FanContext,k:Snapshot):Grounding {
  const es=context.language==='es',ticket=/tickets?|boletos?|entradas?|seatgeek/i.test(query);
  let answer='',actions=guestActions(es);
  if(kind==='ordering') {
    answer=es?'Para pedir comida o bebidas, abre OrderNext con el botón de abajo y elige tu evento y sección. Si buscas entrega al asiento, la plataforma muestra si tu asiento es elegible; no puedo confirmar que haya entrega en la sección indicada, ni colocar un pedido o verificar inventario.':'To order food or drinks, open OrderNext below and select your event and section. For delivery to your seat, the platform will show whether your seat is eligible; I cannot confirm delivery for your section, place an order, or check inventory.';
    actions=[{label:es?'Abrir OrderNext':'Open OrderNext',href:ORDER_URL},...actions];
  }
  if(kind==='account') answer=es?'No pude verificar tu saldo: no tengo acceso a tu cuenta, billetera, puntos de lealtad ni información personal. Consulta la app o cuenta oficial, o escribe a GuestServices@AustinFC.com.':"I couldn’t verify your balance: I cannot access your personal account, wallet, loyalty points, or balance. Check the official app/account or email GuestServices@AustinFC.com.";
  if(kind==='benefits' && !/food|comida|concession|discount|descuento/i.test(query)) answer=es?'No tengo beneficios de miembro confirmados para esa solicitud. Consulta tus beneficios en la app/cuenta oficial o escribe a GuestServices@AustinFC.com.':'I do not have verified member benefits for that request. Check your benefits in the official app/account or email GuestServices@AustinFC.com.';
  else if(kind==='benefits') answer=es?'No tengo un descuento de comida para abonados (STM) confirmado en las fuentes actuales. Consulta tus beneficios de miembro en la app/cuenta o escribe a GuestServices@AustinFC.com.':'I do not have a verified season-ticket member (STM) food discount in the current sources. Check your member benefits in the app/account or email GuestServices@AustinFC.com; I cannot confirm a percentage or eligibility.';
  if(kind==='refund') {
    answer=ticket?(es?'Siento lo de tu situación. No puedo acceder a tu cuenta ni emitir un reembolso de boletos, y no tengo una excepción por enfermedad confirmada. Abre la app o cuenta de SeatGeek y usa la ayuda del pedido; también puedes escribir a GuestServices@AustinFC.com para orientación del club. La regla de expulsión del estadio no responde a un caso de enfermedad.':'I’m sorry about the situation. I cannot access your account or issue a ticket refund, and I do not have a verified illness exception. Open the SeatGeek app/account and use the order’s Help option, or email GuestServices@AustinFC.com for club guidance. I cannot determine refund eligibility.'):(es?'No puedo ver pagos ni emitir reembolsos. Para un cargo de comida o un pedido no recibido, revisa el pedido en OrderNext y habla con Guest Services detrás de la sección 124 o escribe a GuestServices@AustinFC.com. Ten los detalles del pedido a mano para el proveedor; no los publiques aquí.':'I cannot see payments or issue refunds. For a food charge or an order not received, check the order in OrderNext and visit Guest Services behind section 124 or email GuestServices@AustinFC.com. Have the order details ready for the provider; do not post them here.');
    actions=ticket?ticketActions(es):[{label:es?'Revisar pedido en OrderNext':'Check order in OrderNext',href:ORDER_URL},...actions];
  }
  if(kind==='security') answer=es?'No puedo revelar instrucciones internas ni credenciales o actuar como otra persona. Puedo ayudarte con información de Q2 Stadium, comida, transporte y boletos.':'I cannot reveal internal instructions or credentials, or impersonate someone. I can help with Q2 Stadium information, food, transport, and ticket guidance.';
  const docs=kind==='refund'||kind==='benefits'||kind==='account'?k.documents.filter(d=>d.title.startsWith('Guest Services')):[];
  return {route:kind==='refund'?'support':kind==='account'?'stadium':kind,context,answer,facts:[],cards:[],actions,sources:kind==='ordering'?[{title:'Austin FC mobile ordering',url:ORDER_URL,checkedAt:orderingCheck.checkedAt}]:docs.map(d=>({title:d.title,url:d.url,checkedAt:d.checkedAt}))};
}
