import type { FanContext, Grounding } from './types';
import type { Snapshot } from './knowledge';
import { MOBILE_TICKET_URL, TICKET_URL } from './knowledge';
import { ticketActions } from './handoffs';
import { normalized } from './safety';
export function ticketGrounding(query:string,context:FanContext,k:Snapshot):Grounding {
 const q=normalized(query),es=context.language==='es';
 const phoneFailure=/\b(?:phone|cellphone|mobile|telefono|celular)\b.{0,40}(?:dead|died|empty|no power|no battery|no responde|not responding|frozen|apago|sin bateria|agotad)|(?:battery|bateria).{0,30}(?:dead|empty|agotad)/.test(q);
 const barcode=/barcode|bar code|codigo de barras/.test(q);
 const transact=/buy.{0,40}for (?:me|us)|purchase.{0,40}for (?:me|us)|(?:can|could) you.{0,25}(?:buy|purchase|sell|book|transfer)|^(?:please )?(?:buy|purchase|sell|book)\b|buy me|transfer for me|comprame|comprarme|compra.{0,25}por mi|(?:transfiere|transferir|envia|enviar).{0,70}(?:por mi|por favor)/.test(q);
 const transfer=/transfer|traspas|mand\w*|recipient|receive|accept|claim|sent|send|share|enviar|envio|envie|recibir|recibe|acepta/.test(q);
 const hq=k.documents.find(d=>d.title==='SeatGeek Ticket HQ');
 const matchday=phoneFailure||barcode||/gate|puerta|barcode|bar code|screenshot|captura|phone.{0,20}(?:dead|died)|telefono.{0,20}bateria|at (?:the )?stadium|right now|ahora/.test(q);
 const contact=es?'SeatGeek Ticket HQ: 512-953-2858 o tickethq@austinfc.com.':'SeatGeek Ticket HQ: 512-953-2858 or tickethq@austinfc.com.';
 const box=es?'En partidos de Austin FC, la taquilla está al noreste del estadio; abre 3 horas antes del inicio y cierra en el minuto 60. Para otros eventos, confirma el horario específico.':'For Austin FC matches, the Box Office is on the northeast side of the stadium, opens 3 hours before kickoff and closes at the 60th minute. For other events, check the event-specific hours.';
 let answer='';
 if(transact)answer=es?'Usa Austin FC / SeatGeek para comprar o transferir tu boleto. No puedo comprar ni transferir boletos por ti.':'Use Austin FC / SeatGeek to buy or transfer your ticket. I can’t buy or transfer tickets for you.';
 else if(transfer) {
  const sender=es?'Para enviar: en la app Austin FC & Q2 Stadium, abre el boleto del partido, pulsa “Send”, introduce el correo o teléfono del destinatario, selecciona la cantidad y pulsa “Send Tickets”.':'To send: in the Austin FC & Q2 Stadium app, open the match ticket, tap “Send”, enter the recipient’s email or phone number, select the quantity and tap “Send Tickets”.';
  const receiver=es?'Para recibir: confirma con el remitente el correo o teléfono usado y entra a tu propia cuenta de SeatGeek. En la app Austin FC & Q2 Stadium, abre “My Tickets” y “Manage My Tickets”.':'To receive: confirm the email or phone used with the sender and sign in to your own SeatGeek account. In the Austin FC & Q2 Stadium app, open “My Tickets” and “Manage My Tickets”.';
  const receiving=/recipient|receive|accept|claim|recibir|recibe|acepta|destinatario/.test(q),sending=/send|share|enviar|envio|mand\w*|transfer my|transfer a|transfer tickets|transfer.*friend|transferir|traspas/.test(q);
  answer=receiving&&sending?sender+'\n\n'+receiver:receiving?receiver:sender;
  if(/button.{0,25}missing|missing.{0,25}button|button.{0,25}(?:vanished|gone)|cannot transfer|can.t transfer|transfer.{0,20}(?:failed|error)|no aparece.{0,25}(?:send|boton)|(?:boton|enviar).{0,30}no aparece/.test(q))answer=es?'Si falta “Send” o falla la transferencia, abre el boleto en tu cuenta/app de SeatGeek y usa la ayuda del pedido. Ticket HQ puede revisar las restricciones; este asistente no puede cambiarlas.':'If “Send” is missing or the transfer fails, open your ticket in the SeatGeek app and use the order’s Help option. Ticket HQ can review restrictions; this assistant cannot change them.';
 } else if(/screenshot|screen shot|photo.{0,20}(?:ticket|barcode)|foto.{0,20}(?:boleto|entrada)|captura/.test(q))answer=es?'Abre el boleto original en la app oficial de Austin FC / SeatGeek en lugar de depender de una captura del código de barras. Si no puedes mostrarlo al entrar, ve a Ticket HQ.':'Open the original ticket in the official Austin FC / SeatGeek app rather than relying on a barcode screenshot. If you cannot display it at entry, go to Ticket HQ.';
 else if(phoneFailure||barcode)answer=es?'Si tu teléfono se quedó sin batería o el código de barras aparece en blanco en la puerta, pide ayuda al personal de acceso y ve a SeatGeek Ticket HQ en el lado noreste. Ellos pueden revisar tu boleto; no publiques datos de tu cuenta aquí.':'If your phone died or the barcode is blank at the gate, ask entry staff for help and go to SeatGeek Ticket HQ on the northeast side. They can review your ticket; do not post account details here.';
 else if(/facebook|marketplace|resale|resell|scalp|reventa/.test(q))answer=es?'Usa Austin FC / SeatGeek para compras oficiales. Ticket HQ puede orientarte antes de comprar un boleto de reventa; este asistente no puede autenticar una oferta de Facebook Marketplace o garantizar que sea válida.':'Use Austin FC / SeatGeek for official purchases. Ask Ticket HQ before buying a resale ticket; this assistant cannot authenticate a Facebook Marketplace listing or guarantee it is valid.';
 else if(/postpon|cancel|aplaz|pospuest|suspend/.test(q))answer=es?'Consulta el aviso oficial del evento y tu pedido de SeatGeek para saber los pasos por un cambio de fecha. Ticket HQ puede confirmar las opciones para ese boleto; no hay una regla de reembolso verificada para tu caso aquí.':'Check the official event announcement and your SeatGeek order for instructions after a date change. Ticket HQ can confirm options for that ticket; this assistant does not have verified refund eligibility for your case.';
 else if(/price|cost|how much|discount|student|military|precio|cuesta|descuento|estudiante|militar/.test(q))answer=es?'Los precios y descuentos dependen del evento y del boleto. Revisa las ofertas actuales de Austin FC / SeatGeek y consulta a Ticket HQ sobre descuentos de estudiantes o militares; no hay un precio o descuento confirmado para esta solicitud.':'Prices and discounts depend on the event and ticket. Check current Austin FC / SeatGeek listings and ask Ticket HQ about student or military offers; no price or discount is verified for this request.';
 else if(/sign.?in|log.?in|password|recover|account|cuenta|contrasena/.test(q))answer=es?'Abre tu cuenta/app de SeatGeek y usa su ayuda para iniciar sesión o recuperar acceso. Ticket HQ puede ayudarte con tus boletos; este asistente no accede a cuentas personales.':'Open your SeatGeek account/app and use Help for sign-in or access recovery. Ticket HQ can help with your tickets; this assistant cannot access personal accounts.';
 else answer=es?'Abre Austin FC / SeatGeek para comprar o gestionar boletos. Para una duda o problema específico, contacta a SeatGeek Ticket HQ.':'Open Austin FC / SeatGeek to buy or manage tickets. For a specific ticket question or problem, contact SeatGeek Ticket HQ.';
 if(matchday)answer+='\n\n'+box;
 answer+='\n\n'+contact;
 const contactOnly=/contact|support.*(?:phone|number)|(?:actual )?ticket support|ticket hq/.test(q)&&!transfer&&!transact;
 const sources=[...(contactOnly?[]:transfer?[{title:'Austin FC mobile ticketing',url:MOBILE_TICKET_URL,checkedAt:k.checkedAt}]:[{title:'Austin FC tickets',url:TICKET_URL,checkedAt:k.checkedAt}]),...(hq?[{title:hq.title,url:hq.url,checkedAt:hq.checkedAt}]:[])];
 return {route:transact?'transaction':'ticketing',context,answer,facts:[],cards:[],sources,actions:[{label:es?'Comprar boletos oficiales':'Buy official tickets',href:TICKET_URL},{label:es?'Llamar a Ticket HQ':'Call Ticket HQ',href:'tel:5129532858'},{label:es?'Correo a Ticket HQ':'Email Ticket HQ',href:'mailto:tickethq@austinfc.com'},...ticketActions(es)]};
}
