'use client';
import { useState } from 'react';
import type { Draft } from '@/lib/feed-workflow';
import '../../style.css';
import '../../guide/guide.css';
export default function KnowledgeAdmin(){
  const [token,setToken]=useState(''),[person,setPerson]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[cursor,setCursor]=useState<string|null>(null);
  const [entry,setEntry]=useState(JSON.stringify({id:'member-food-benefit',title:'Member food benefit',topic:'benefits',keywords:['STM food discount','descuento de comida para abonados'],answer:{en:'Replace this with the club-approved public answer.',es:'Reemplaza este texto con la respuesta pública aprobada por el club.'},sourceUrl:'https://www.austinfc.com/',expiresAt:new Date(Date.now()+30*86400000).toISOString(),actions:[]},null,2));
  async function call(method:string,body?:object,append=false){setBusy(true);setStatus('');try{const r=await fetch('/api/internal-knowledge/drafts'+(append&&cursor?'?cursor='+encodeURIComponent(cursor):''),{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');if(d.drafts){setDrafts(old=>append?[...old,...d.drafts]:d.drafts);setCursor(d.cursor);}setStatus(d.status?`Entry ${d.status}. Published content may take up to 60 seconds to refresh.`:'Drafts loaded.');}catch(e){setStatus(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
  return <main className="guide-page"><div className="guide-wrap"><a href="/guide?topic=internal">← Club knowledge</a><h1>Submit and review club knowledge</h1><p>Drafts stay private until a different reviewer approves them. Only approved, unexpired English and Spanish answers appear for fans. Do not submit personal or confidential information.</p><label htmlFor="staff-token">Staff access key (submission or reviewer key)</label><input id="staff-token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/><label htmlFor="staff-name">Your name / role</label><input id="staff-name" value={person} onChange={e=>setPerson(e.target.value)}/><p>The key stays in this page’s memory and is never placed in a URL or local storage. Reviewer access is required to list or approve drafts.</p><form onSubmit={e=>{e.preventDefault();try{void call('POST',{submittedBy:person,entry:JSON.parse(entry)});}catch{setStatus('Invalid JSON.');}}}><label htmlFor="entry">Entry JSON</label><textarea id="entry" rows={18} style={{width:'100%',fontFamily:'monospace'}} value={entry} onChange={e=>setEntry(e.target.value)}/><button disabled={busy||!token||person.length<3}>Submit private draft</button></form><p role="status">{status}</p><button disabled={busy||!token} onClick={()=>call('GET')}>Load review queue</button>{drafts.map(d=><article className="guide-card" key={d.id}><h2>{d.entry.title}</h2><p>{d.status} · submitted by {d.submittedBy}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(d.entry,null,2)}</pre>{['pending','publishing'].includes(d.status)&&<div className="handoffs"><button disabled={busy||person.length<3} onClick={()=>call('PATCH',{id:d.id,reviewedBy:person,decision:'approve'})}>Approve and publish</button><button disabled={busy||person.length<3} onClick={()=>call('PATCH',{id:d.id,reviewedBy:person,decision:'reject'})}>Reject</button></div>}</article>)}{cursor&&<button disabled={busy} onClick={()=>call('GET',undefined,true)}>Load more drafts</button>}</div></main>;
}
